### ISSUE TITLE
Figure out correct Guid format for MongoDB Ids

### ISSUE THREAD

**Issue by adamhomer88** [RedSyndicate/GardenerMultitool#49]
![image](https://user-images.githubusercontent.com/2982406/150920061-edba6467-7902-4dfc-9ddd-cd9e5efb5a8c.png)
https://github.com/RedSyndicate/GardenerMultitool/pull/45/files

potential problem
CSV -> JSON -> Mongo -> id(string rep of guid)

potential fixerooni
CSV -> JSON -> Mongo -> _id(ObjectID) with no id(GUID)

**Comment by KungRaseri** [comment]
Some reference: https://mongodb.github.io/mongo-csharp-driver/2.11/reference/bson/guidserialization/serializerchanges/guidserializerchanges/
